FROM rust:1.69

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    libasound2-dev \
    libudev-dev \
    jackd2 \
    libjack-jackd2-dev \
    libgl1-mesa-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libx11-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup default nightly