FROM rust:1.69

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    libasound2-dev \
    libudev-dev \
    jackd2 \
    libjack-jackd2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup default nightly