default_platform(:ios)

platform :ios do
  lane :dev do
    setup_ci if ENV["CI"]

    match(type: "appstore")

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false,
    )

    build_app(scheme: "Bloop")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    match(type: "appstore")

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false,
    )

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"],
      xcodeproj: "Bloop.xcodeproj"
    )

    build_app(scheme: "Bloop")
    
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end