default_platform(:ios)

platform :ios do
  lane :dev do
    match(type: "development")
    build_app(scheme: "Bloop")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    create_keychain(
      name: "fastlane_tmp",
      password: "fastlane",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      type: "appstore",
      readonly: true,
      keychain_name: "fastlane_tmp",
      keychain_password: "fastlane"
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false,
    )
  
    build_number = ENV["BUILD_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")
    increment_build_number(
      build_number: build_number,
      xcodeproj: "Bloop.xcodeproj"
    )
  
    build_app(scheme: "Bloop")
    
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end