# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :dev do
    match(type: "development")
    build_app(scheme: "Bloop")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    match(type: "adhoc", readonly: true)
    
    build_number = ENV["BUILD_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")
    increment_build_number(
      build_number: build_number,
      xcodeproj: "Bloop.xcodeproj"
    )

    build_app(scheme: "Bloop")

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )
    upload_to_testflight(api_key: api_key)
  end
end
